### ISSUE TITLE
Script is having trouble locating the timezone and country code

### ISSUE THREAD

**Issue by viper12887** [TorZidan/TeslaWatch#1]
Hey Im a total n00b at script writing but I desperate want to get this to work.  

Im getting blocked because the script is having trouble locating the timezone and country code. Is there a way to update the script to allow me to manually enter the location instead of needing pull from the tesla api?

<img width="734" alt="Screenshot 2024-07-01 at 4 05 17 PM" src="https://github.com/TorZidan/TeslaWatch/assets/174390181/453f7dc6-3709-45c9-8fb2-a80a89d997f2">

**Comment by tpape2** [comment]
Same here

**Comment by sar838** [comment]
I am getting the same url error as viper12887.

**Comment by TorZidan** [comment]
Omg! I had setup a separate email for Github stuff, and had forgotten to check it. Apologies.
Apparently Tesla made a change in their APIs few months ago, and the script stopped working.

I fixed it and it works well for me. Please give it a try. You will need to copy/paste all code from file TeslaSolarWatch.gs into the same file in your AppsScript project. Good luck and thanks for all the fish!

**Comment by TorZidan** [comment]
I am going to close this issue.
I haven't heard back , but it works for me.
